### ISSUE TITLE
devops: icos.cpauth Keeps old systemd service config

### ISSUE THREAD

**Issue by mirzov** [ICOS-Carbon-Portal/infrastructure#10]
Currently cpauth.service has policy of restarting on abort, whereas other jar services have restart: always. This difference prevented cpauth from starting up after the last power blackout. Re-deploying cpauth from SBT (with -tcpauth_only option) does not update the systemd config. Full re-deploying failed because of #9 .

**Comment by andreby** [comment]
All services now have "Restart=always" and the changes have been deployed.
